### ISSUE TITLE
one object with multi model 

### ISSUE THREAD

**Issue by ghoshaw** [kirumang/Pix2Pose#11]
Hi, 
    I have a question about the train data generating.  For one object, like a cup, I use depth sensor to reconstruct a lot 3D models, and how could I create the train data pairs in a consistent style.   I mean that each model of the cup is in different locations in world coords. If I  can directly use the script in tools? or I have to transform the model to same position and then run the scripts?

**Comment by kirumang** [comment]
Hi,
In my opinion, the best way is to align the models in the same coordinate frame (a consistent origin and the same axis directions). And, you have to assign normalized coordinate values of each vertex. you can either use each 3D model for the corresponding images or use one model for all scenes using the pose information obtained during the alignment of models. For the first case,  ```2_1_ply_file_to_3d_coord_model.py```  should be updated to have the fixed center points(x_ct,y_ct,z_ct) and dimensions(x_abs,y_abs,z_abs) instead of computing them for each model as is in the current code. 

I think what you are doing is a very interesting way to collect training images!
I am happy to help if you have further questions or supports.

**Comment by ghoshaw** [comment]
thanks
